name: Build and Release Tournament Bracket Generator

on:
  push:
    tags:
      - "v*" # Trigger only on version tags, e.g., v1.0.0
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    name: Build Executables
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        target:
          ubuntu-latest: x86_64-unknown-linux-gnu
          windows-latest: x86_64-pc-windows-msvc
          macos-latest: x86_64-apple-darwin
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target[matrix.os] }}

      - name: Build executable
        run: cargo build --release --target=${{ matrix.target[matrix.os] }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-tournament_bracket_generator
          path: |
            target/${{ matrix.target[matrix.os] }}/release/tournament_bracket_generator*
            # Includes the executable with appropriate file extensions

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts/

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            -t "Tournament Bracket Generator ${{ github.ref_name }}" \
            -n "Release notes for version ${{ github.ref_name }}. Built for Windows, Linux, and macOS." \
            artifacts/*
